version: "3.6"

services:
  postgres:
    restart: unless-stopped
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    image: ${APP_NAME}-postgres:latest
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  fastapi:
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    image: ${APP_NAME}-fastapi:latest
    volumes:
      - .:/run
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING}
    working_dir: /run
    ports:
        - "8009:80"
    tty:
        true
    networks:
      - mynetwork

  redis:
    restart: unless-stopped
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    image: ${APP_NAME}-redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

volumes:
  postgres: