version: "3.6"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database-test
    env_file:
      - '.env'
    working_dir: /run
    networks:
      - mynetwork
    tty:
        true
  database-test:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
        - "5433:5432"
