version: "3.6"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database
    env_file:
      - '.env'
    working_dir: /run
    entrypoint: [ "uvicorn", "--host", "0.0.0.0", "--port", "80", "src.app.main:app", "--reload" ]
    networks:
      - mynetwork
    ports:
        - "8009:80"
    tty:
        true
  database:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5437:5432"
    networks:
      - mynetwork
volumes:
  postgres-data:
    name: "postgres_data"
networks:
  mynetwork:
    driver: bridge
