version: "3.6"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database
    env_file:
      - '.env'
    working_dir: /run
    networks:
      - mynetwork
    tty:
        true
  database:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    networks:
      - mynetwork
volumes:
  postgres-data:
    name: "postgres_data"
networks:
  mynetwork:
    driver: bridge
