version: "3.6"

services:
  postgres:
    restart: unless-stopped
    image: ${REGISTRY_NAME}/tsd-project/postgres:latest
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  fastapi:
    image: ${REGISTRY_NAME}/tsd-project/fastapi:latest
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING}
    ports:
        - "8009:80"
    tty:
        true
    networks:
      - mynetwork

  redis:
    restart: unless-stopped
    image: ${REGISTRY_NAME}/tsd-project/redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - fastapi
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

volumes:
  postgres:
