name: Deployment from Github to AWS
on:
  push:
    branches:
      - main
      - 2-upgrade-docker-compose-environment-for-backend

env:
  AWS_REGION: eu-central-1

jobs:
  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: tsd-project
        run: |
          docker build -t tsd-project/fastapi -f ./docker/fastapi/Dockerfile .
          docker tag tsd-project/fastapi:latest $ECR_REGISTRY/tsd-project/fastapi:latest
          docker push $ECR_REGISTRY/tsd-project/fastapi:latest

          docker build -t tsd-project/postgres -f ./docker/postgres/Dockerfile ./docker/postgres
          docker tag tsd-project/postgres:latest $ECR_REGISTRY/tsd-project/postgres:latest
          docker push $ECR_REGISTRY/tsd-project/postgres:latest

          docker build -t tsd-project/redis -f ./docker/redis/Dockerfile ./docker/redis
          docker tag tsd-project/redis:latest $ECR_REGISTRY/tsd-project/redis:latest
          docker push $ECR_REGISTRY/tsd-project/redis:latest

      - name: Run command on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            source /home/ubuntu/tsd-project/setup.sh
            sudo docker-compose -f /home/ubuntu/tsd-project/docker-compose.yml down
            sudo docker-compose -f /home/ubuntu/tsd-project/docker-compose.yml pull
            sudo docker-compose -f /home/ubuntu/tsd-project/docker-compose.yml up -d